INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_COMPETITION competition)

FIND_PATH(
    COMPETITION_INCLUDE_DIRS
    NAMES competition/api.h
    HINTS $ENV{COMPETITION_DIR}/include
        ${PC_COMPETITION_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    COMPETITION_LIBRARIES
    NAMES gnuradio-competition
    HINTS $ENV{COMPETITION_DIR}/lib
        ${PC_COMPETITION_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(COMPETITION DEFAULT_MSG COMPETITION_LIBRARIES COMPETITION_INCLUDE_DIRS)
MARK_AS_ADVANCED(COMPETITION_LIBRARIES COMPETITION_INCLUDE_DIRS)

